name: Cleanup GHCR Images

on:
  workflow_dispatch:
  schedule:
    - cron: '15 5 1 * *'

jobs:
  cleanup:
    name: Cleanup old container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Apply container retention policy
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: cloudflare-dns-api
          image-tags: "!latest"
          cut-off: 90d
          keep-n-most-recent: 10